# Server
server.port=8080

# Application
spring.application.name=gateway

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[1].id=order-service-graphql
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/graphql

spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=orders
springdoc.swagger-ui.urls[0].url=/api/orders/api-docs
springdoc.swagger-ui.urls[1].name=notifications
springdoc.swagger-ui.urls[1].url=/api/notifications/api-docs

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


springdoc.swagger-ui.config-url=/aggregated-api-docs

