# Server
server.port=8081

# Application
spring.application.name=order-service

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# gRPC Server
grpc.server.port=9091
grpc.client.kitchen.host=localhost
grpc.client.kitchen.port=9092
grpc.client.delivery.host=localhost
grpc.client.delivery.port=9093

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.servlet.exception-handlers-enabled=true
spring.graphql.graphiql.enabled=false

# GraphQL эндпоинт
spring.graphql.path=/graphql